apiVersion: v2
name: traccar
description: A Helm chart for Traccar GPS Server
type: application
version: 1.10.0
appVersion: "5.10"
dependencies:
  - name: mariadb
    version: 18.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis-ha
    version: 4.23.0
    repository: https://dandydeveloper.github.io/charts
    condition: redis-ha.enabled
maintainers:
  - email: laszlo.kondas@gmail.com
    name: kondas
