apiVersion: v2
name: traccar
description: A Helm chart for Traccar GPS Server
type: application
version: 1.9.1
appVersion: "5.10"
dependencies:
  - name: mysql
    version: 3.1.0
    repository: https://groundhog2k.github.io/helm-charts/
    condition: mysql.enabled
  - name: redis-ha
    version: 4.23.0
    repository: https://dandydeveloper.github.io/charts
    condition: redis-ha.enabled
maintainers:
  - email: laszlo.kondas@gmail.com
    name: kondas
